In [ ]:
# Question # 1:
#Demonstrate NumPy array creation methods and basic operations.

# Instructions:
# 1. Import NumPy as np.
# 2. Create the following arrays:
#    - Array A: 1D array from list [2,4,6,8,10,12,14,16,18,20]
#    - Array B: 3x3 array of zeros
#    - Array C: 5 random integers between 1 and 100
#    - Array D: 10 evenly spaced numbers between 0 and 5 using np.linspace()

# 3. For Array A print:
#    - Shape
#    - Data type
#    - Size
#    - Number of dimensions

# 4. Perform operations on Array A:
#    - Reshape to 2x5
#    - Find max value and index
#    - Find min value and index

# 5. Create Array E = [[1,2,3],[4,5,6],[7,8,9]]
#    Print element at row 1 column 2.


In [1]:
import numpy as np

# Arrays
A = np.array([2,4,6,8,10,12,14,16,18,20])
B = np.zeros((3,3))
C = np.random.randint(1,101,5)
D = np.linspace(0,5,10)

print("A:",A)
print("B:\n",B)
print("C:",C)
print("D:",D)

# Properties of A
print("Shape:",A.shape)
print("Datatype:",A.dtype)
print("Size:",A.size)
print("Dimensions:",A.ndim)

# Operations
print("Reshape:\n",A.reshape(2,5))
print("Max:",A.max(),"Index:",A.argmax())
print("Min:",A.min(),"Index:",A.argmin())

# Array E
E = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Element (row1,col2):",E[1,2])

A: [ 2  4  6  8 10 12 14 16 18 20]
B:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
C: [20 40 49 22 90]
D: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Shape: (10,)
Datatype: int64
Size: 10
Dimensions: 1
Reshape:
 [[ 2  4  6  8 10]
 [12 14 16 18 20]]
Max: 20 Index: 9
Min: 2 Index: 0
Element (row1,col2): 6


In [ ]:
# Question # 2:Demonstrate broadcasting and universal functions.

# Instructions:
# 1. Import NumPy as np.
# 2. Create:
#    arr1 = [[1,2,3],[4,5,6]]
#    arr2 = [10,20,30]

# 3. Perform:
#    - Addition
#    - Subtraction
#    - Multiplication
#    - Division

# 4. Explain broadcasting in a comment.

# 5. Create arr3 = [1,4,9,16,25] and apply:
#    - np.sqrt()
#    - np.exp()
#    - np.sin()

# 6. Create arr4 = [[5,12,3],[8,2,7]] and demonstrate:
#    - Sum of all elements
#    - Max in each column
#    - Min in each row

# 7. Convert arr1 to float using type casting.

In [2]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])

# Broadcasting:
print("Addition:\n", arr1 + arr2)
print("Subtraction:\n", arr1 - arr2)
print("Multiplication:\n", arr1 * arr2)
print("Division:\n", arr1 / arr2)

arr3 = np.array([1,4,9,16,25])
print("sqrt:", np.sqrt(arr3))
print("exp:", np.exp(arr3))
print("sin:", np.sin(arr3))

arr4 = np.array([[5,12,3],[8,2,7]])
print("Sum:", np.sum(arr4))
print("Max column:", np.max(arr4, axis=0))
print("Min row:", np.min(arr4, axis=1))

# Type casting
arr1_float = arr1.astype(float)
print("arr1 as float:\n", arr1_float)

Addition:
 [[11 22 33]
 [14 25 36]]
Subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]]
Multiplication:
 [[ 10  40  90]
 [ 40 100 180]]
Division:
 [[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]
sqrt: [1. 2. 3. 4. 5.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Sum: 37
Max column: [ 8 12  7]
Min row: [3 2]
arr1 as float:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
# Question # 3:Perform basic exploratory data analysis using Pandas.

# Instructions:
# 1. Import pandas as pd and numpy as np.

# 2. Create dictionary:

# data = {
# 'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
# 'Age': [25,30,np.nan,35,28,np.nan],
# 'Score': [85,92,78,np.nan,88,95],
# 'Grade': ['A','A','B','C','B','A']
# }

# 3. Create DataFrame df.

# 4. Perform:
#    - df.head(3)
#    - df.shape
#    - df.columns
#    - df.dtypes

# 5. Missing data:
#    - df.isnull()
#    - Fill Age with mean
#    - Drop rows with missing Score

# 6. Selection:
#    - Select Name and Score
#    - Select rows where Score > 85
#    - Set Name as index

# 7. Operations:
#    - Unique grades
#    - Grade counts
#    - Sort by Score descending


In [2]:
import pandas as pd
import numpy as np

#Create dictionary
data = {
    'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
    'Age': [25,30,np.nan,35,28,np.nan],
    'Score': [85,92,78,np.nan,88,95],
    'Grade': ['A','A','B','C','B','A']
}
#Create DataFrame
df = pd.DataFrame(data)
#Basic Data Information
print("First 3 rows:")
print(df.head(3))
print("\nShape:")
print(df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

#Missing Data Handling

# Check missing values
print("\nMissing Values:")
print(df.isnull())

# Fill Age with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Drop rows where Score is missing
df = df.dropna(subset=['Score'])

print("\nData after handling missing values:")
print(df)

# Select Name and Score columns
print("\nName and Score:")
print(df[['Name','Score']])

# Rows where Score > 85
print("\nScore greater than 85:")
print(df[df['Score'] > 85])

# Set Name as index
df = df.set_index('Name')

print("\nData with Name as index:")
print(df)

# Unique grades
print("\nUnique Grades:")
print(df['Grade'].unique())

# Grade counts
print("\nGrade Counts:")
print(df['Grade'].value_counts())

# Sort by Score descending
print("\nSorted by Score (Descending):")
print(df.sort_values(by='Score', ascending=False))

First 3 rows:
      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B

Shape:
(6, 4)

Columns:
Index(['Name', 'Age', 'Score', 'Grade'], dtype='str')

Data Types:
Name         str
Age      float64
Score    float64
Grade        str
dtype: object

Missing Values:
    Name    Age  Score  Grade
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3  False  False   True  False
4  False  False  False  False
5  False   True  False  False

Data after handling missing values:
      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A

Name and Score:
      Name  Score
0    Alice   85.0
1      Bob   92.0
2  Charlie   78.0
4      Eve   88.0
5    Frank   95.0

Score greater than 85:
    Name   Age  Score Grade
1    Bob  30.0   92.0     A
4    Eve  28.0   88.0     B
5  Frank  29.5 